name: yolo_deploy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy<2.0.0
    - ultralytics>=8.2.0
    - opencv-python>=4.10.0
    - onnx==1.16.1
    - tritonclient[all]==2.48.0