name: yolo_deploy_env
channels:
  - defaults
dependencies:
  - onnxruntime=1.18
  - pip
  - pytorch=2.4
  - onnx=1.16.1
  - pytorch-cuda=11.8
  - torchvision=0.19
  - python=3.10
  - opencv[version='>=4.10.0']
  - cuda-toolkit=11.8
